version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: nexus_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: nexus_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-init:/docker-entrypoint-initdb.d

  redis:
    image: redis:7-alpine
    container_name: nexus_redis
    restart: always
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
